#!/bin/bash

cd "${0%/*}"

sed -i '/^[^#]/d' PKGBUILD
printf "pkgver=%s\n" "$(date '+%Y%m%d')" >> PKGBUILD
for sum_type in sha256 md5; do
  printf "%ssums=('%s')\n" \
    "${sum_type}" \
    "$(
      ${sum_type}sum mirrorlist | \
        awk '{print $1}'
    )" >> PKGBUILD
done
